# Generated by Django 6.0.2 on 2026-02-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("unidade_medida", models.CharField(max_length=20)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tempo_trabalho_horas",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "valor_hora_trabalho",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "margem_lucro_percentual",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                (
                    "preco_final",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemComposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_utilizada",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atelier.material",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="atelier.produto",
                    ),
                ),
            ],
        ),
    ]
