# Generated by Django 6.0.2 on 2026-02-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="margem_lucro_percentual",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="produto",
            name="valor_hora_trabalho",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
