# Generated by Django 6.0.2 on 2026-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0002_alter_produto_margem_lucro_percentual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="desconto_valor",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Desconto em Reais",
                max_digits=10,
            ),
        ),
    ]
