# Generated by Django 6.0.2 on 2026-02-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0003_produto_desconto_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem_frente",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem_lado",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem_tras",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
    ]
