# Generated by Django 6.0.2 on 2026-02-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0004_produto_imagem_frente_produto_imagem_lado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="valor_hora_trabalho",
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10),
        ),
    ]
