# Generated by Django 6.0.2 on 2026-02-23 00:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0005_alter_produto_valor_hora_trabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="estoque_minimo",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="material",
            name="quantidade_estoque",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_venda", models.DateTimeField(default=django.utils.timezone.now)),
                ("valor_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("CREDITO", "Cartão de Crédito"),
                            ("DEBITO", "Cartão de Débito"),
                            ("DINHEIRO", "Dinheiro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="atelier.produto",
                    ),
                ),
            ],
        ),
    ]
