# Generated by Django 6.0.2 on 2026-02-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "atelier",
            "0006_material_estoque_minimo_material_quantidade_estoque_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="nome_cliente",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
