# Generated by Django 6.0.2 on 2026-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0007_venda_nome_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="telefone_cliente",
            field=models.CharField(
                blank=True,
                help_text="Ex: 51999999999 (Apenas números com DDD)",
                max_length=20,
                null=True,
                verbose_name="Telefone/WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="nome_cliente",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome do Cliente"
            ),
        ),
    ]
