# Generated by Django 6.0.2 on 2026-02-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0008_venda_telefone_cliente_alter_venda_nome_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_adicionada",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_unitario_na_compra",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço pago por unidade nesta compra",
                        max_digits=10,
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="atelier.material",
                    ),
                ),
            ],
        ),
    ]
