# Generated by Django 6.0.2 on 2026-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0009_entradamaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("metro", "Metro"),
                    ("unidade", "Unidade"),
                    ("rolo", "Rolo"),
                    ("quilo", "Quilo"),
                    ("grama", "Grama"),
                ],
                max_length=20,
            ),
        ),
    ]
