# Generated by Django 6.0.2 on 2026-02-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0010_alter_material_unidade_medida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="desconto_valor",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Desconto em Reais",
                max_digits=10,
                verbose_name="Desconto (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="Descrição do Produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="margem_lucro_percentual",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                max_digits=5,
                verbose_name="Margem de Lucro (%)",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do Produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tempo_trabalho_horas",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="Tempo de Trabalho (Horas)",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="valor_hora_trabalho",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                max_digits=10,
                verbose_name="Hora de Trabalho (R$)",
            ),
        ),
    ]
