# Generated by Django 6.0.2 on 2026-02-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "atelier",
            "0011_alter_produto_desconto_valor_alter_produto_descricao_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiais",
                to="atelier.categoriamaterial",
            ),
        ),
    ]
