# Generated by Django 6.0.2 on 2026-03-01 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0013_cliente_remove_venda_nome_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tempo_trabalho_horas",
            field=models.TimeField(
                default=datetime.time(0, 0), verbose_name="Tempo de Trabalho (Horas)"
            ),
        ),
    ]
