# Generated by Django 6.0.2 on 2026-03-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier", "0014_alter_produto_tempo_trabalho_horas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unidade_medida",
            field=models.CharField(
                choices=[
                    ("metro", "Metro"),
                    ("centímetro", "Centímetro"),
                    ("milímetro", "Milímetro"),
                    ("unidade", "Unidade"),
                    ("rolo", "Rolo"),
                    ("quilo", "Quilo"),
                    ("grama", "Grama"),
                    ("carretel", "Carretel"),
                ],
                max_length=20,
            ),
        ),
    ]
